# Generated by Django 3.2.3 on 2021-06-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('resenia', models.TextField(max_length=1500)),
                ('foto', models.ImageField(upload_to='pelicula')),
                ('actores', models.ManyToManyField(to='movie_database.Actor')),
            ],
        ),
    ]
